adds validations
patricknikolaus/kitchenbff-back pull request #22
Opened 2022-07-19 23:29 UTC by fellowbeard

2022-07-22 23:44 UTC, fellowbeard commented
Are you getting this message?

2022-07-23 00:11 UTC, patricknikolaus requested changes

2022-07-23 00:11 UTC, dampdump commented on app/models/ingredient.rb
> +  validates_length_of :ingredient, minimum: 0
Since measurement is an integer the validation for num: min-max looks a little different.
Replace lines 3 & 4 with `validates :measurement, numericality: {less_than: 100_000_000, greater_than: 0}`

2022-08-17 18:31 UTC, patricknikolaus approved these changes

2022-08-17 18:31 UTC, merged